const fantasyHorrorBooks = [
    {
        id: 1,
        title: "El Señor de los Anillos",
        description: "Una épica historia de fantasía sobre la lucha entre el bien y el mal en la Tierra Media.",
        price: "$19.99",
        imagen: "https://images-na.ssl-images-amazon.com/images/I/51EstVXM1UL._SX331_BO1,204,203,200_.jpg",
        category: "Fantasía",
    },
    {
        id: 2,
        title: "Drácula",
        description: "Una clásica novela de terror que narra la lucha contra el legendario vampiro Drácula.",
        price: "$14.99",
        imagen: "https://images-na.ssl-images-amazon.com/images/I/41+eK8zBwQL._SX331_BO1,204,203,200_.jpg",
        category: "Terror",
    },
    {
        id: 3,
        title: "Juego de Tronos",
        description: "Primera entrega de la saga 'Canción de Hielo y Fuego', llena de intrigas y luchas por el poder.",
        price: "$24.99",
        imagen: "https://images.cdn2.buscalibre.com/fit-in/360x360/a9/38/a938366ae95be88c1c6350f7a727026a.jpg",
        category: "Fantasía",
    },
    {
        id: 4,
        title: "It",
        description: "Novela de terror que narra los enfrentamientos de un grupo de amigos con una entidad maligna.",
        price: "$22.99",
        imagen: "https://images.cdn1.buscalibre.com/fit-in/360x360/c8/e8/c8e8567ca80b4bb032e5390c7e1b012d.jpg",
        category: "Terror",
    },  
    {   
        id: 5,
        title: "El Hobbit",
        description: "La historia de un hobbit llamado Bilbo que se embarca en una gran aventura.",
        price: "$18.99",
        imagen: "https://images-na.ssl-images-amazon.com/images/I/51b5YG6Y1rL._SX331_BO1,204,203,200_.jpg",
        category: "Fantasía",
    },  
    {   
        id: 6,
        title: "Frankenstein",
        description: "La icónica novela sobre el científico Victor Frankenstein y su monstruosa creación.",
        price: "$16.99",
        imagen: "https://cdn.prod.website-files.com/6034d7d1f3e0f52c50b2adee/625452f43a8fa502af2b8a14_6034d7d1f3e0f525c6b2b272_frankenstein-mary-shelley-editorial-alma.jpeg",
        category: "Terror",
    },  
    {   
        id: 7,
        title: "La Sombra sobre Innsmouth",
        description: "Una aterradora historia corta de H.P. Lovecraft sobre horrores cósmicos.",
        price: "$12.99",
        imagen: "https://images.cdn2.buscalibre.com/fit-in/360x360/17/60/1760689cf1faf34cc5952245d5be8dae.jpg",
        category: "Terror",
    },  
    {   
        id: 8,
        title: "Crónicas de Narnia: El León, la Bruja y el Ropero",
        description: "El primer libro de la serie de fantasía, donde cuatro niños descubren un mundo mágico.",
        price: "$17.99",
        imagen: "https://images.cdn1.buscalibre.com/fit-in/360x360/3e/d1/3ed17c865085a0e86f93037e16d20257.jpg",
        category: "Fantasía",
    },  
    {   
        id: 9,
        title: "El Resplandor",
        description: "Una novela de terror psicológico que sigue la espiral de locura de Jack Torrance en un hotel aislado.",
        price: "$19.99",
        imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyxMZbnlAmDMT2Cj4AnarrDdWI6VYMupvnNQ&s",
        category: "Terror",
    },  
    {   
        id: 10,
        title: "Harry Potter y la Piedra Filosofal",
        description: "El primer libro de la saga de fantasía sobre un joven mago que descubre sus poderes.",
        price: "$14.99",
        imagen: "https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg",
        category: "Fantasía",
    },
];

export default fantasyHorrorBooks;